# Generated by Django 4.2 on 2023-06-28 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Productmodel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=255)),
                ('Product', models.CharField(max_length=255)),
                ('State', models.CharField(max_length=255)),
                ('DateofDelivery', models.CharField(max_length=255)),
                ('DateofShipping', models.CharField(max_length=255)),
                ('Status', models.CharField(max_length=255)),
                ('AmountPaid', models.CharField(max_length=255)),
                ('PendingAmount', models.CharField(max_length=255)),
                ('Date', models.CharField(max_length=255)),
                ('ShippingMode', models.CharField(max_length=255)),
            ],
        ),
    ]
