# Generated by Django 4.2 on 2023-06-28 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_rename_amountpaid_productmodel_amountpaid_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productmodel',
            old_name='State',
            new_name='state',
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='id',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
