# Generated by Django 4.2 on 2023-07-02 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_calendarmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='calendarmodel',
            old_name='end_date',
            new_name='date',
        ),
        migrations.RemoveField(
            model_name='calendarmodel',
            name='start_date',
        ),
    ]
